/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../../app/components/app.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '@angular/core/src/linker/view_type';
import * as import6 from '@angular/core/src/change_detection/change_detection';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from '../../../app/services/picture.service';
import * as import9 from '../../../app/services/auth.service';
import * as import10 from './css/app.component.css.shim';
import * as import11 from '@angular/core/src/linker/query_list';
import * as import12 from '@angular/core/src/linker/view_container';
import * as import13 from '../../node_modules/@angular/common/src/directives/ng_if.ngfactory';
import * as import14 from 'ng2-bs3-modal/components/modal';
import * as import15 from '../../node_modules/ng2-bs3-modal/components/modal.ngfactory';
import * as import16 from '../../node_modules/@angular/forms/src/directives/ng_form.ngfactory';
import * as import17 from '../../node_modules/@angular/forms/src/directives/ng_control_status.ngfactory';
import * as import18 from 'ng2-bs3-modal/components/modal-header';
import * as import19 from '../../node_modules/ng2-bs3-modal/components/modal-header.ngfactory';
import * as import20 from 'ng2-bs3-modal/components/modal-body';
import * as import21 from '../../node_modules/ng2-bs3-modal/components/modal-body.ngfactory';
import * as import22 from '../../node_modules/@angular/forms/src/directives/default_value_accessor.ngfactory';
import * as import23 from '../../node_modules/@angular/forms/src/directives/validators.ngfactory';
import * as import24 from '../../node_modules/@angular/forms/src/directives/ng_model.ngfactory';
import * as import25 from 'ng2-bs3-modal/components/modal-footer';
import * as import26 from '../../node_modules/ng2-bs3-modal/components/modal-footer.ngfactory';
import * as import27 from '../../node_modules/@angular/common/src/directives/ng_for.ngfactory';
import * as import28 from '../../../app/pipes/sort.pipe';
import * as import29 from '../../../app/pipes/author.pipe';
import * as import30 from '@angular/core/src/linker/template_ref';
import * as import31 from '@angular/core/src/linker/element_ref';
import * as import32 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import33 from '@angular/common/src/directives/ng_if';
import * as import34 from '@angular/forms/src/directives/default_value_accessor';
import * as import35 from '@angular/forms/src/directives/validators';
import * as import36 from '@angular/forms/src/validators';
import * as import37 from '@angular/forms/src/directives/control_value_accessor';
import * as import38 from '@angular/forms/src/directives/ng_model';
import * as import39 from '@angular/forms/src/directives/ng_control';
import * as import40 from '@angular/forms/src/directives/ng_control_status';
import * as import41 from '@angular/forms/src/directives/ng_form';
import * as import42 from '@angular/forms/src/directives/control_container';
import * as import43 from '@angular/common/src/directives/ng_for';
import * as import44 from '../../../app/components/brick.component';
import * as import45 from './brick.component.ngfactory';
export class Wrapper_AppComponent {
  /*private*/ _eventHandler:Function;
  context:import0.AppComponent;
  /*private*/ _changed:boolean;
  constructor(p0:any,p1:any) {
    this._changed = false;
    this.context = new import0.AppComponent(p0,p1);
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_AppComponent_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_AppComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.AppComponent>;
  _AppComponent_0_3:Wrapper_AppComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_AppComponent_Host0,renderType_AppComponent_Host,import5.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'app',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_AppComponent0(this.viewUtils,this,0,this._el_0);
    this._AppComponent_0_3 = new Wrapper_AppComponent(this.injectorGet(import8.PictureService,this.parentIndex),this.injectorGet(import9.AuthService,this.parentIndex));
    this.compView_0.create(this._AppComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._AppComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.AppComponent) && (0 === requestNodeIndex))) { return this._AppComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._AppComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.detectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const AppComponentNgFactory:import7.ComponentFactory<import0.AppComponent> = new import7.ComponentFactory<import0.AppComponent>('app',View_AppComponent_Host0,import0.AppComponent);
const styles_AppComponent:any[] = [import10.styles];
var renderType_AppComponent:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.Emulated,styles_AppComponent,{});
export class View_AppComponent0 extends import1.AppView<import0.AppComponent> {
  _viewQuery_picModal_0:import11.QueryList<any>;
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _text_11:any;
  _el_12:any;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _el_16:any;
  _text_17:any;
  _text_18:any;
  _el_19:any;
  _text_20:any;
  _text_21:any;
  _text_22:any;
  _text_23:any;
  _el_24:any;
  _text_25:any;
  _el_26:any;
  _text_27:any;
  _anchor_28:any;
  /*private*/ _vc_28:import12.ViewContainer;
  _TemplateRef_28_5:any;
  _NgIf_28_6:import13.Wrapper_NgIf;
  _text_29:any;
  _el_30:any;
  _text_31:any;
  _el_32:any;
  _text_33:any;
  _el_34:any;
  _text_35:any;
  _el_36:any;
  _text_37:any;
  _el_38:any;
  _el_39:any;
  _text_40:any;
  _anchor_41:any;
  /*private*/ _vc_41:import12.ViewContainer;
  _TemplateRef_41_5:any;
  _NgIf_41_6:import13.Wrapper_NgIf;
  _text_42:any;
  _el_43:any;
  _el_44:any;
  _text_45:any;
  _anchor_46:any;
  /*private*/ _vc_46:import12.ViewContainer;
  _TemplateRef_46_5:any;
  _NgIf_46_6:import13.Wrapper_NgIf;
  _text_47:any;
  _el_48:any;
  _el_49:any;
  _text_50:any;
  _anchor_51:any;
  /*private*/ _vc_51:import12.ViewContainer;
  _TemplateRef_51_5:any;
  _NgIf_51_6:import13.Wrapper_NgIf;
  _text_52:any;
  _text_53:any;
  _text_54:any;
  _anchor_55:any;
  /*private*/ _vc_55:import12.ViewContainer;
  _TemplateRef_55_5:any;
  _NgIf_55_6:import13.Wrapper_NgIf;
  _text_56:any;
  _text_57:any;
  _el_58:any;
  _text_59:any;
  _anchor_60:any;
  /*private*/ _vc_60:import12.ViewContainer;
  _TemplateRef_60_5:any;
  _NgIf_60_6:import13.Wrapper_NgIf;
  _text_61:any;
  _anchor_62:any;
  /*private*/ _vc_62:import12.ViewContainer;
  _TemplateRef_62_5:any;
  _NgIf_62_6:import13.Wrapper_NgIf;
  _text_63:any;
  _text_64:any;
  _text_65:any;
  _text_66:any;
  _text_67:any;
  _text_68:any;
  _text_69:any;
  _el_70:any;
  compView_70:import1.AppView<import14.ModalComponent>;
  _ModalComponent_70_3:import15.Wrapper_ModalComponent;
  _text_71:any;
  _el_72:any;
  _NgForm_72_3:import16.Wrapper_NgForm;
  _ControlContainer_72_4:any;
  _NgControlStatusGroup_72_5:import17.Wrapper_NgControlStatusGroup;
  _text_73:any;
  _el_74:any;
  compView_74:import1.AppView<import18.ModalHeaderComponent>;
  _ModalHeaderComponent_74_3:import19.Wrapper_ModalHeaderComponent;
  _text_75:any;
  _el_76:any;
  _text_77:any;
  _text_78:any;
  _text_79:any;
  _el_80:any;
  compView_80:import1.AppView<import20.ModalBodyComponent>;
  _ModalBodyComponent_80_3:import21.Wrapper_ModalBodyComponent;
  _text_81:any;
  _el_82:any;
  _text_83:any;
  _el_84:any;
  _text_85:any;
  _text_86:any;
  _el_87:any;
  _DefaultValueAccessor_87_3:import22.Wrapper_DefaultValueAccessor;
  _RequiredValidator_87_4:import23.Wrapper_RequiredValidator;
  _NG_VALIDATORS_87_5:any[];
  _NG_VALUE_ACCESSOR_87_6:any[];
  _NgModel_87_7:import24.Wrapper_NgModel;
  _NgControl_87_8:any;
  _NgControlStatus_87_9:import17.Wrapper_NgControlStatus;
  _text_88:any;
  _text_89:any;
  _el_90:any;
  _text_91:any;
  _el_92:any;
  _text_93:any;
  _text_94:any;
  _el_95:any;
  _DefaultValueAccessor_95_3:import22.Wrapper_DefaultValueAccessor;
  _RequiredValidator_95_4:import23.Wrapper_RequiredValidator;
  _NG_VALIDATORS_95_5:any[];
  _NG_VALUE_ACCESSOR_95_6:any[];
  _NgModel_95_7:import24.Wrapper_NgModel;
  _NgControl_95_8:any;
  _NgControlStatus_95_9:import17.Wrapper_NgControlStatus;
  _text_96:any;
  _text_97:any;
  _text_98:any;
  _el_99:any;
  compView_99:import1.AppView<import25.ModalFooterComponent>;
  _ModalFooterComponent_99_3:import26.Wrapper_ModalFooterComponent;
  _text_100:any;
  _el_101:any;
  _text_102:any;
  _text_103:any;
  _el_104:any;
  _text_105:any;
  _text_106:any;
  _text_107:any;
  _text_108:any;
  _text_109:any;
  _el_110:any;
  _text_111:any;
  _anchor_112:any;
  /*private*/ _vc_112:import12.ViewContainer;
  _TemplateRef_112_5:any;
  _NgFor_112_6:import27.Wrapper_NgFor;
  _text_113:any;
  _text_114:any;
  /*private*/ _expr_165:any;
  _pipe_sort_0:import28.SortPipe;
  _pipe_whose_1:import29.AuthorPipe;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_AppComponent0,renderType_AppComponent,import5.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
    this._expr_165 = import6.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._viewQuery_picModal_0 = new import11.QueryList<any>();
    this._el_0 = import3.createRenderElement(this.renderer,parentRenderNode,'nav',new import3.InlineArray2(2,'class','navbar navbar-default navbar-fixed-top'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','container-fluid'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._text_4 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._el_5 = import3.createRenderElement(this.renderer,this._el_2,'div',new import3.InlineArray2(2,'class','navbar-header'),(null as any));
    this._text_6 = this.renderer.createText(this._el_5,'\n      ',(null as any));
    this._el_7 = import3.createRenderElement(this.renderer,this._el_5,'button',new import3.InlineArray16(10,'aria-expanded','false','class','navbar-toggle collapsed','data-target','#bs-example-navbar-collapse-1','data-toggle','collapse','type','button'),(null as any));
    this._text_8 = this.renderer.createText(this._el_7,'\n        ',(null as any));
    this._el_9 = import3.createRenderElement(this.renderer,this._el_7,'span',new import3.InlineArray2(2,'class','sr-only'),(null as any));
    this._text_10 = this.renderer.createText(this._el_9,'Toggle navigation',(null as any));
    this._text_11 = this.renderer.createText(this._el_7,'\n        ',(null as any));
    this._el_12 = import3.createRenderElement(this.renderer,this._el_7,'span',new import3.InlineArray2(2,'class','icon-bar'),(null as any));
    this._text_13 = this.renderer.createText(this._el_7,'\n        ',(null as any));
    this._el_14 = import3.createRenderElement(this.renderer,this._el_7,'span',new import3.InlineArray2(2,'class','icon-bar'),(null as any));
    this._text_15 = this.renderer.createText(this._el_7,'\n        ',(null as any));
    this._el_16 = import3.createRenderElement(this.renderer,this._el_7,'span',new import3.InlineArray2(2,'class','icon-bar'),(null as any));
    this._text_17 = this.renderer.createText(this._el_7,'\n      ',(null as any));
    this._text_18 = this.renderer.createText(this._el_5,'\n      ',(null as any));
    this._el_19 = import3.createRenderElement(this.renderer,this._el_5,'a',new import3.InlineArray4(4,'class','navbar-brand','href','#'),(null as any));
    this._text_20 = this.renderer.createText(this._el_19,'Pineclone',(null as any));
    this._text_21 = this.renderer.createText(this._el_5,'\n    ',(null as any));
    this._text_22 = this.renderer.createText(this._el_2,'\n\n    ',(null as any));
    this._text_23 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._el_24 = import3.createRenderElement(this.renderer,this._el_2,'div',new import3.InlineArray4(4,'class','collapse navbar-collapse','id','bs-example-navbar-collapse-1'),(null as any));
    this._text_25 = this.renderer.createText(this._el_24,'\n      ',(null as any));
    this._el_26 = import3.createRenderElement(this.renderer,this._el_24,'ul',new import3.InlineArray2(2,'class','nav navbar-nav'),(null as any));
    this._text_27 = this.renderer.createText(this._el_26,'\n        ',(null as any));
    this._anchor_28 = this.renderer.createTemplateAnchor(this._el_26,(null as any));
    this._vc_28 = new import12.ViewContainer(28,26,this,this._anchor_28);
    this._TemplateRef_28_5 = new import30.TemplateRef_(this,28,this._anchor_28);
    this._NgIf_28_6 = new import13.Wrapper_NgIf(this._vc_28.vcRef,this._TemplateRef_28_5);
    this._text_29 = this.renderer.createText(this._el_26,'\n        ',(null as any));
    this._el_30 = import3.createRenderElement(this.renderer,this._el_26,'li',new import3.InlineArray2(2,'class','dropdown'),(null as any));
    this._text_31 = this.renderer.createText(this._el_30,'\n          ',(null as any));
    this._el_32 = import3.createRenderElement(this.renderer,this._el_30,'a',new import3.InlineArray16(12,'aria-expanded','false','aria-haspopup','true','class','dropdown-toggle','data-toggle','dropdown','href','#','role','button'),(null as any));
    this._text_33 = this.renderer.createText(this._el_32,'Sort',(null as any));
    this._el_34 = import3.createRenderElement(this.renderer,this._el_32,'span',new import3.InlineArray2(2,'class','caret'),(null as any));
    this._text_35 = this.renderer.createText(this._el_30,'\n          ',(null as any));
    this._el_36 = import3.createRenderElement(this.renderer,this._el_30,'ul',new import3.InlineArray2(2,'class','dropdown-menu'),(null as any));
    this._text_37 = this.renderer.createText(this._el_36,'\n            ',(null as any));
    this._el_38 = import3.createRenderElement(this.renderer,this._el_36,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_39 = import3.createRenderElement(this.renderer,this._el_38,'a',new import3.InlineArray2(2,'href','#'),(null as any));
    this._text_40 = this.renderer.createText(this._el_39,'by author ',(null as any));
    this._anchor_41 = this.renderer.createTemplateAnchor(this._el_39,(null as any));
    this._vc_41 = new import12.ViewContainer(41,39,this,this._anchor_41);
    this._TemplateRef_41_5 = new import30.TemplateRef_(this,41,this._anchor_41);
    this._NgIf_41_6 = new import13.Wrapper_NgIf(this._vc_41.vcRef,this._TemplateRef_41_5);
    this._text_42 = this.renderer.createText(this._el_36,'\n            ',(null as any));
    this._el_43 = import3.createRenderElement(this.renderer,this._el_36,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_44 = import3.createRenderElement(this.renderer,this._el_43,'a',new import3.InlineArray2(2,'href','#'),(null as any));
    this._text_45 = this.renderer.createText(this._el_44,'by likes ',(null as any));
    this._anchor_46 = this.renderer.createTemplateAnchor(this._el_44,(null as any));
    this._vc_46 = new import12.ViewContainer(46,44,this,this._anchor_46);
    this._TemplateRef_46_5 = new import30.TemplateRef_(this,46,this._anchor_46);
    this._NgIf_46_6 = new import13.Wrapper_NgIf(this._vc_46.vcRef,this._TemplateRef_46_5);
    this._text_47 = this.renderer.createText(this._el_36,'\n            ',(null as any));
    this._el_48 = import3.createRenderElement(this.renderer,this._el_36,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_49 = import3.createRenderElement(this.renderer,this._el_48,'a',new import3.InlineArray2(2,'href','#'),(null as any));
    this._text_50 = this.renderer.createText(this._el_49,'by date posted ',(null as any));
    this._anchor_51 = this.renderer.createTemplateAnchor(this._el_49,(null as any));
    this._vc_51 = new import12.ViewContainer(51,49,this,this._anchor_51);
    this._TemplateRef_51_5 = new import30.TemplateRef_(this,51,this._anchor_51);
    this._NgIf_51_6 = new import13.Wrapper_NgIf(this._vc_51.vcRef,this._TemplateRef_51_5);
    this._text_52 = this.renderer.createText(this._el_36,'\n          ',(null as any));
    this._text_53 = this.renderer.createText(this._el_30,'\n        ',(null as any));
    this._text_54 = this.renderer.createText(this._el_26,'\n        ',(null as any));
    this._anchor_55 = this.renderer.createTemplateAnchor(this._el_26,(null as any));
    this._vc_55 = new import12.ViewContainer(55,26,this,this._anchor_55);
    this._TemplateRef_55_5 = new import30.TemplateRef_(this,55,this._anchor_55);
    this._NgIf_55_6 = new import13.Wrapper_NgIf(this._vc_55.vcRef,this._TemplateRef_55_5);
    this._text_56 = this.renderer.createText(this._el_26,'\n      ',(null as any));
    this._text_57 = this.renderer.createText(this._el_24,'\n      ',(null as any));
    this._el_58 = import3.createRenderElement(this.renderer,this._el_24,'ul',new import3.InlineArray2(2,'class','nav navbar-nav navbar-right'),(null as any));
    this._text_59 = this.renderer.createText(this._el_58,'\n        ',(null as any));
    this._anchor_60 = this.renderer.createTemplateAnchor(this._el_58,(null as any));
    this._vc_60 = new import12.ViewContainer(60,58,this,this._anchor_60);
    this._TemplateRef_60_5 = new import30.TemplateRef_(this,60,this._anchor_60);
    this._NgIf_60_6 = new import13.Wrapper_NgIf(this._vc_60.vcRef,this._TemplateRef_60_5);
    this._text_61 = this.renderer.createText(this._el_58,'\n        ',(null as any));
    this._anchor_62 = this.renderer.createTemplateAnchor(this._el_58,(null as any));
    this._vc_62 = new import12.ViewContainer(62,58,this,this._anchor_62);
    this._TemplateRef_62_5 = new import30.TemplateRef_(this,62,this._anchor_62);
    this._NgIf_62_6 = new import13.Wrapper_NgIf(this._vc_62.vcRef,this._TemplateRef_62_5);
    this._text_63 = this.renderer.createText(this._el_58,'\n      ',(null as any));
    this._text_64 = this.renderer.createText(this._el_24,'\n    ',(null as any));
    this._text_65 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._text_66 = this.renderer.createText(this._el_2,'\n  ',(null as any));
    this._text_67 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._text_68 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_69 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_70 = import3.createRenderElement(this.renderer,parentRenderNode,'modal',new import3.InlineArray8(6,'class','modal','role','dialog','tabindex','-1'),(null as any));
    this.compView_70 = new import15.View_ModalComponent0(this.viewUtils,this,70,this._el_70);
    this._ModalComponent_70_3 = new import15.Wrapper_ModalComponent(new import31.ElementRef(this._el_70));
    this._text_71 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._el_72 = import3.createRenderElement(this.renderer,(null as any),'form',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._NgForm_72_3 = new import16.Wrapper_NgForm((null as any),(null as any));
    this._ControlContainer_72_4 = this._NgForm_72_3.context;
    this._NgControlStatusGroup_72_5 = new import17.Wrapper_NgControlStatusGroup(this._ControlContainer_72_4);
    this._text_73 = this.renderer.createText(this._el_72,'\n    ',(null as any));
    this._el_74 = import3.createRenderElement(this.renderer,this._el_72,'modal-header',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_74 = new import19.View_ModalHeaderComponent0(this.viewUtils,this,74,this._el_74);
    this._ModalHeaderComponent_74_3 = new import19.Wrapper_ModalHeaderComponent(this._ModalComponent_70_3.context);
    this._text_75 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_76 = import3.createRenderElement(this.renderer,(null as any),'h4',new import3.InlineArray2(2,'class','modal-title'),(null as any));
    this._text_77 = this.renderer.createText(this._el_76,'Add a picture',(null as any));
    this._text_78 = this.renderer.createText((null as any),'\n    ',(null as any));
    this.compView_74.create(this._ModalHeaderComponent_74_3.context);
    this._text_79 = this.renderer.createText(this._el_72,'\n    ',(null as any));
    this._el_80 = import3.createRenderElement(this.renderer,this._el_72,'modal-body',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_80 = new import21.View_ModalBodyComponent0(this.viewUtils,this,80,this._el_80);
    this._ModalBodyComponent_80_3 = new import21.Wrapper_ModalBodyComponent();
    this._text_81 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_82 = import3.createRenderElement(this.renderer,(null as any),'div',new import3.InlineArray2(2,'class','form-group'),(null as any));
    this._text_83 = this.renderer.createText(this._el_82,'\n        ',(null as any));
    this._el_84 = import3.createRenderElement(this.renderer,this._el_82,'label',new import3.InlineArray2(2,'for','firstName'),(null as any));
    this._text_85 = this.renderer.createText(this._el_84,'URL',(null as any));
    this._text_86 = this.renderer.createText(this._el_82,'\n        ',(null as any));
    this._el_87 = import3.createRenderElement(this.renderer,this._el_82,'input',new import3.InlineArray16(10,'class','form-control','id','url','name','url','required','','type','text'),(null as any));
    this._DefaultValueAccessor_87_3 = new import22.Wrapper_DefaultValueAccessor(this.renderer,new import31.ElementRef(this._el_87));
    this._RequiredValidator_87_4 = new import23.Wrapper_RequiredValidator();
    this._NG_VALIDATORS_87_5 = [this._RequiredValidator_87_4.context];
    this._NG_VALUE_ACCESSOR_87_6 = [this._DefaultValueAccessor_87_3.context];
    this._NgModel_87_7 = new import24.Wrapper_NgModel(this._ControlContainer_72_4,this._NG_VALIDATORS_87_5,(null as any),this._NG_VALUE_ACCESSOR_87_6);
    this._NgControl_87_8 = this._NgModel_87_7.context;
    this._NgControlStatus_87_9 = new import17.Wrapper_NgControlStatus(this._NgControl_87_8);
    this._text_88 = this.renderer.createText(this._el_82,'\n      ',(null as any));
    this._text_89 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_90 = import3.createRenderElement(this.renderer,(null as any),'div',new import3.InlineArray2(2,'class','form-group'),(null as any));
    this._text_91 = this.renderer.createText(this._el_90,'\n        ',(null as any));
    this._el_92 = import3.createRenderElement(this.renderer,this._el_90,'label',new import3.InlineArray2(2,'for','lastName'),(null as any));
    this._text_93 = this.renderer.createText(this._el_92,'Description',(null as any));
    this._text_94 = this.renderer.createText(this._el_90,'\n        ',(null as any));
    this._el_95 = import3.createRenderElement(this.renderer,this._el_90,'input',new import3.InlineArray16(10,'class','form-control','id','description','name','description','required','','type','text'),(null as any));
    this._DefaultValueAccessor_95_3 = new import22.Wrapper_DefaultValueAccessor(this.renderer,new import31.ElementRef(this._el_95));
    this._RequiredValidator_95_4 = new import23.Wrapper_RequiredValidator();
    this._NG_VALIDATORS_95_5 = [this._RequiredValidator_95_4.context];
    this._NG_VALUE_ACCESSOR_95_6 = [this._DefaultValueAccessor_95_3.context];
    this._NgModel_95_7 = new import24.Wrapper_NgModel(this._ControlContainer_72_4,this._NG_VALIDATORS_95_5,(null as any),this._NG_VALUE_ACCESSOR_95_6);
    this._NgControl_95_8 = this._NgModel_95_7.context;
    this._NgControlStatus_95_9 = new import17.Wrapper_NgControlStatus(this._NgControl_95_8);
    this._text_96 = this.renderer.createText(this._el_90,'\n      ',(null as any));
    this._text_97 = this.renderer.createText((null as any),'\n    ',(null as any));
    this.compView_80.create(this._ModalBodyComponent_80_3.context);
    this._text_98 = this.renderer.createText(this._el_72,'\n    ',(null as any));
    this._el_99 = import3.createRenderElement(this.renderer,this._el_72,'modal-footer',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_99 = new import26.View_ModalFooterComponent0(this.viewUtils,this,99,this._el_99);
    this._ModalFooterComponent_99_3 = new import26.Wrapper_ModalFooterComponent(this._ModalComponent_70_3.context);
    this._text_100 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_101 = import3.createRenderElement(this.renderer,(null as any),'button',new import3.InlineArray8(6,'class','btn btn-default','data-dismiss','modal','type','button'),(null as any));
    this._text_102 = this.renderer.createText(this._el_101,'Cancel',(null as any));
    this._text_103 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_104 = import3.createRenderElement(this.renderer,(null as any),'button',new import3.InlineArray4(4,'class','btn btn-primary','type','button'),(null as any));
    this._text_105 = this.renderer.createText(this._el_104,'Save',(null as any));
    this._text_106 = this.renderer.createText((null as any),'\n    ',(null as any));
    this.compView_99.create(this._ModalFooterComponent_99_3.context);
    this._text_107 = this.renderer.createText(this._el_72,'\n  ',(null as any));
    this._text_108 = this.renderer.createText((null as any),'\n',(null as any));
    this.compView_70.create(this._ModalComponent_70_3.context);
    this._text_109 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_110 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray4(4,'class','container','id','gallery'),(null as any));
    this._text_111 = this.renderer.createText(this._el_110,'\n  ',(null as any));
    this._anchor_112 = this.renderer.createTemplateAnchor(this._el_110,(null as any));
    this._vc_112 = new import12.ViewContainer(112,110,this,this._anchor_112);
    this._TemplateRef_112_5 = new import30.TemplateRef_(this,112,this._anchor_112);
    this._NgFor_112_6 = new import27.Wrapper_NgFor(this._vc_112.vcRef,this._TemplateRef_112_5,this.parentView.injectorGet(import32.IterableDiffers,this.parentIndex),this.ref);
    this._text_113 = this.renderer.createText(this._el_110,'\n',(null as any));
    this._text_114 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_39,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_39));
    var disposable_1:Function = import3.subscribeToRenderElement(this,this._el_44,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_44));
    var disposable_2:Function = import3.subscribeToRenderElement(this,this._el_49,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_49));
    var disposable_3:Function = import3.subscribeToRenderElement(this,this._el_72,new import3.InlineArray4(4,'submit',(null as any),'reset',(null as any)),this.eventHandler(this.handleEvent_72));
    var disposable_4:Function = import3.subscribeToRenderElement(this,this._el_87,new import3.InlineArray8(6,'ngModelChange',(null as any),'input',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_87));
    this._NgModel_87_7.subscribe(this,this.eventHandler(this.handleEvent_87),true);
    var disposable_5:Function = import3.subscribeToRenderElement(this,this._el_95,new import3.InlineArray8(6,'ngModelChange',(null as any),'input',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_95));
    this._NgModel_95_7.subscribe(this,this.eventHandler(this.handleEvent_95),true);
    var disposable_6:Function = import3.subscribeToRenderElement(this,this._el_101,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_101));
    var disposable_7:Function = import3.subscribeToRenderElement(this,this._el_104,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_104));
    this._pipe_sort_0 = new import28.SortPipe();
    this._pipe_whose_1 = new import29.AuthorPipe();
    this._viewQuery_picModal_0.reset([this._ModalComponent_70_3.context]);
    this.context.modal = this._viewQuery_picModal_0.first;
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._text_21,
      this._text_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._anchor_28,
      this._text_29,
      this._el_30,
      this._text_31,
      this._el_32,
      this._text_33,
      this._el_34,
      this._text_35,
      this._el_36,
      this._text_37,
      this._el_38,
      this._el_39,
      this._text_40,
      this._anchor_41,
      this._text_42,
      this._el_43,
      this._el_44,
      this._text_45,
      this._anchor_46,
      this._text_47,
      this._el_48,
      this._el_49,
      this._text_50,
      this._anchor_51,
      this._text_52,
      this._text_53,
      this._text_54,
      this._anchor_55,
      this._text_56,
      this._text_57,
      this._el_58,
      this._text_59,
      this._anchor_60,
      this._text_61,
      this._anchor_62,
      this._text_63,
      this._text_64,
      this._text_65,
      this._text_66,
      this._text_67,
      this._text_68,
      this._text_69,
      this._el_70,
      this._text_71,
      this._el_72,
      this._text_73,
      this._el_74,
      this._text_75,
      this._el_76,
      this._text_77,
      this._text_78,
      this._text_79,
      this._el_80,
      this._text_81,
      this._el_82,
      this._text_83,
      this._el_84,
      this._text_85,
      this._text_86,
      this._el_87,
      this._text_88,
      this._text_89,
      this._el_90,
      this._text_91,
      this._el_92,
      this._text_93,
      this._text_94,
      this._el_95,
      this._text_96,
      this._text_97,
      this._text_98,
      this._el_99,
      this._text_100,
      this._el_101,
      this._text_102,
      this._text_103,
      this._el_104,
      this._text_105,
      this._text_106,
      this._text_107,
      this._text_108,
      this._text_109,
      this._el_110,
      this._text_111,
      this._anchor_112,
      this._text_113,
      this._text_114
    ]
    ),[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4,
      disposable_5,
      disposable_6,
      disposable_7
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import30.TemplateRef) && (28 === requestNodeIndex))) { return this._TemplateRef_28_5; }
    if (((token === import33.NgIf) && (28 === requestNodeIndex))) { return this._NgIf_28_6.context; }
    if (((token === import30.TemplateRef) && (41 === requestNodeIndex))) { return this._TemplateRef_41_5; }
    if (((token === import33.NgIf) && (41 === requestNodeIndex))) { return this._NgIf_41_6.context; }
    if (((token === import30.TemplateRef) && (46 === requestNodeIndex))) { return this._TemplateRef_46_5; }
    if (((token === import33.NgIf) && (46 === requestNodeIndex))) { return this._NgIf_46_6.context; }
    if (((token === import30.TemplateRef) && (51 === requestNodeIndex))) { return this._TemplateRef_51_5; }
    if (((token === import33.NgIf) && (51 === requestNodeIndex))) { return this._NgIf_51_6.context; }
    if (((token === import30.TemplateRef) && (55 === requestNodeIndex))) { return this._TemplateRef_55_5; }
    if (((token === import33.NgIf) && (55 === requestNodeIndex))) { return this._NgIf_55_6.context; }
    if (((token === import30.TemplateRef) && (60 === requestNodeIndex))) { return this._TemplateRef_60_5; }
    if (((token === import33.NgIf) && (60 === requestNodeIndex))) { return this._NgIf_60_6.context; }
    if (((token === import30.TemplateRef) && (62 === requestNodeIndex))) { return this._TemplateRef_62_5; }
    if (((token === import33.NgIf) && (62 === requestNodeIndex))) { return this._NgIf_62_6.context; }
    if (((token === import18.ModalHeaderComponent) && ((74 <= requestNodeIndex) && (requestNodeIndex <= 78)))) { return this._ModalHeaderComponent_74_3.context; }
    if (((token === import34.DefaultValueAccessor) && (87 === requestNodeIndex))) { return this._DefaultValueAccessor_87_3.context; }
    if (((token === import35.RequiredValidator) && (87 === requestNodeIndex))) { return this._RequiredValidator_87_4.context; }
    if (((token === import36.NG_VALIDATORS) && (87 === requestNodeIndex))) { return this._NG_VALIDATORS_87_5; }
    if (((token === import37.NG_VALUE_ACCESSOR) && (87 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_87_6; }
    if (((token === import38.NgModel) && (87 === requestNodeIndex))) { return this._NgModel_87_7.context; }
    if (((token === import39.NgControl) && (87 === requestNodeIndex))) { return this._NgControl_87_8; }
    if (((token === import40.NgControlStatus) && (87 === requestNodeIndex))) { return this._NgControlStatus_87_9.context; }
    if (((token === import34.DefaultValueAccessor) && (95 === requestNodeIndex))) { return this._DefaultValueAccessor_95_3.context; }
    if (((token === import35.RequiredValidator) && (95 === requestNodeIndex))) { return this._RequiredValidator_95_4.context; }
    if (((token === import36.NG_VALIDATORS) && (95 === requestNodeIndex))) { return this._NG_VALIDATORS_95_5; }
    if (((token === import37.NG_VALUE_ACCESSOR) && (95 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_95_6; }
    if (((token === import38.NgModel) && (95 === requestNodeIndex))) { return this._NgModel_95_7.context; }
    if (((token === import39.NgControl) && (95 === requestNodeIndex))) { return this._NgControl_95_8; }
    if (((token === import40.NgControlStatus) && (95 === requestNodeIndex))) { return this._NgControlStatus_95_9.context; }
    if (((token === import20.ModalBodyComponent) && ((80 <= requestNodeIndex) && (requestNodeIndex <= 97)))) { return this._ModalBodyComponent_80_3.context; }
    if (((token === import25.ModalFooterComponent) && ((99 <= requestNodeIndex) && (requestNodeIndex <= 106)))) { return this._ModalFooterComponent_99_3.context; }
    if (((token === import41.NgForm) && ((72 <= requestNodeIndex) && (requestNodeIndex <= 107)))) { return this._NgForm_72_3.context; }
    if (((token === import42.ControlContainer) && ((72 <= requestNodeIndex) && (requestNodeIndex <= 107)))) { return this._ControlContainer_72_4; }
    if (((token === import40.NgControlStatusGroup) && ((72 <= requestNodeIndex) && (requestNodeIndex <= 107)))) { return this._NgControlStatusGroup_72_5.context; }
    if (((token === import14.ModalComponent) && ((70 <= requestNodeIndex) && (requestNodeIndex <= 108)))) { return this._ModalComponent_70_3.context; }
    if (((token === import30.TemplateRef) && (112 === requestNodeIndex))) { return this._TemplateRef_112_5; }
    if (((token === import43.NgFor) && (112 === requestNodeIndex))) { return this._NgFor_112_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const valUnwrapper:any = new import6.ValueUnwrapper();
    const currVal_28_0_0:any = (this.context.user? this.context.user.authenticated: false);
    this._NgIf_28_6.check_ngIf(currVal_28_0_0,throwOnChange,false);
    this._NgIf_28_6.ngDoCheck(this,this._anchor_28,throwOnChange);
    const currVal_41_0_0:any = (this.context.choice === 'author');
    this._NgIf_41_6.check_ngIf(currVal_41_0_0,throwOnChange,false);
    this._NgIf_41_6.ngDoCheck(this,this._anchor_41,throwOnChange);
    const currVal_46_0_0:any = (this.context.choice === 'likes');
    this._NgIf_46_6.check_ngIf(currVal_46_0_0,throwOnChange,false);
    this._NgIf_46_6.ngDoCheck(this,this._anchor_46,throwOnChange);
    const currVal_51_0_0:any = (this.context.choice === 'createdOn');
    this._NgIf_51_6.check_ngIf(currVal_51_0_0,throwOnChange,false);
    this._NgIf_51_6.ngDoCheck(this,this._anchor_51,throwOnChange);
    const currVal_55_0_0:any = (this.context.user? this.context.user.authenticated: false);
    this._NgIf_55_6.check_ngIf(currVal_55_0_0,throwOnChange,false);
    this._NgIf_55_6.ngDoCheck(this,this._anchor_55,throwOnChange);
    const currVal_60_0_0:boolean = (this.context.user? !this.context.user.authenticated: true);
    this._NgIf_60_6.check_ngIf(currVal_60_0_0,throwOnChange,false);
    this._NgIf_60_6.ngDoCheck(this,this._anchor_60,throwOnChange);
    const currVal_62_0_0:any = (this.context.user? this.context.user.authenticated: false);
    this._NgIf_62_6.check_ngIf(currVal_62_0_0,throwOnChange,false);
    this._NgIf_62_6.ngDoCheck(this,this._anchor_62,throwOnChange);
    this._ModalComponent_70_3.ngDoCheck(this,this._el_70,throwOnChange);
    this._NgForm_72_3.ngDoCheck(this,this._el_72,throwOnChange);
    this._NgControlStatusGroup_72_5.ngDoCheck(this,this._el_72,throwOnChange);
    const currVal_74_0_0:any = true;
    this._ModalHeaderComponent_74_3.check_showClose(currVal_74_0_0,throwOnChange,false);
    this._ModalHeaderComponent_74_3.ngDoCheck(this,this._el_74,throwOnChange);
    this._ModalBodyComponent_80_3.ngDoCheck(this,this._el_80,throwOnChange);
    this._DefaultValueAccessor_87_3.ngDoCheck(this,this._el_87,throwOnChange);
    const currVal_87_1_0:any = '';
    this._RequiredValidator_87_4.check_required(currVal_87_1_0,throwOnChange,false);
    this._RequiredValidator_87_4.ngDoCheck(this,this._el_87,throwOnChange);
    const currVal_87_2_0:any = 'url';
    this._NgModel_87_7.check_name(currVal_87_2_0,throwOnChange,false);
    const currVal_87_2_1:any = this.context.upload.url;
    this._NgModel_87_7.check_model(currVal_87_2_1,throwOnChange,false);
    this._NgModel_87_7.ngDoCheck(this,this._el_87,throwOnChange);
    this._NgControlStatus_87_9.ngDoCheck(this,this._el_87,throwOnChange);
    this._DefaultValueAccessor_95_3.ngDoCheck(this,this._el_95,throwOnChange);
    const currVal_95_1_0:any = '';
    this._RequiredValidator_95_4.check_required(currVal_95_1_0,throwOnChange,false);
    this._RequiredValidator_95_4.ngDoCheck(this,this._el_95,throwOnChange);
    const currVal_95_2_0:any = 'description';
    this._NgModel_95_7.check_name(currVal_95_2_0,throwOnChange,false);
    const currVal_95_2_1:any = this.context.upload.description;
    this._NgModel_95_7.check_model(currVal_95_2_1,throwOnChange,false);
    this._NgModel_95_7.ngDoCheck(this,this._el_95,throwOnChange);
    this._NgControlStatus_95_9.ngDoCheck(this,this._el_95,throwOnChange);
    this._ModalFooterComponent_99_3.ngDoCheck(this,this._el_99,throwOnChange);
    valUnwrapper.reset();
    const currVal_112_0_0:any = valUnwrapper.unwrap(this._pipe_whose_1.transform(valUnwrapper.unwrap(this._pipe_sort_0.transform(this.context.pictures,this.context.choice)),this.context.type,this.context.author));
    this._NgFor_112_6.check_ngForOf(currVal_112_0_0,throwOnChange,valUnwrapper.hasWrappedValue);
    this._NgFor_112_6.ngDoCheck(this,this._anchor_112,throwOnChange);
    this._vc_28.detectChangesInNestedViews(throwOnChange);
    this._vc_41.detectChangesInNestedViews(throwOnChange);
    this._vc_46.detectChangesInNestedViews(throwOnChange);
    this._vc_51.detectChangesInNestedViews(throwOnChange);
    this._vc_55.detectChangesInNestedViews(throwOnChange);
    this._vc_60.detectChangesInNestedViews(throwOnChange);
    this._vc_62.detectChangesInNestedViews(throwOnChange);
    this._vc_112.detectChangesInNestedViews(throwOnChange);
    this._ModalComponent_70_3.checkHost(this,this.compView_70,this._el_70,throwOnChange);
    this._NgControlStatusGroup_72_5.checkHost(this,this,this._el_72,throwOnChange);
    this._RequiredValidator_87_4.checkHost(this,this,this._el_87,throwOnChange);
    this._NgControlStatus_87_9.checkHost(this,this,this._el_87,throwOnChange);
    this._RequiredValidator_95_4.checkHost(this,this,this._el_95,throwOnChange);
    this._NgControlStatus_95_9.checkHost(this,this,this._el_95,throwOnChange);
    const currVal_165:boolean = !this._NgForm_72_3.context.valid;
    if (import3.checkBinding(throwOnChange,this._expr_165,currVal_165)) {
      this.renderer.setElementProperty(this._el_104,'disabled',currVal_165);
      this._expr_165 = currVal_165;
    }
    this.compView_70.detectChanges(throwOnChange);
    this.compView_74.detectChanges(throwOnChange);
    this.compView_80.detectChanges(throwOnChange);
    this.compView_99.detectChanges(throwOnChange);
  }
  destroyInternal():void {
    this._vc_28.destroyNestedViews();
    this._vc_41.destroyNestedViews();
    this._vc_46.destroyNestedViews();
    this._vc_51.destroyNestedViews();
    this._vc_55.destroyNestedViews();
    this._vc_60.destroyNestedViews();
    this._vc_62.destroyNestedViews();
    this._vc_112.destroyNestedViews();
    this.compView_70.destroy();
    this.compView_74.destroy();
    this.compView_80.destroy();
    this.compView_99.destroy();
    this._NgModel_87_7.ngOnDestroy();
    this._NgModel_95_7.ngOnDestroy();
    this._NgForm_72_3.ngOnDestroy();
    this._ModalComponent_70_3.ngOnDestroy();
  }
  visitProjectableNodesInternal(nodeIndex:number,ngContentIndex:number,cb:any,ctx:any):void {
    if (((nodeIndex == 70) && (ngContentIndex == 0))) {
      cb(this._text_71,ctx);
      cb(this._el_72,ctx);
      cb(this._text_108,ctx);
    }
    if (((nodeIndex == 74) && (ngContentIndex == 0))) {
      cb(this._text_75,ctx);
      cb(this._el_76,ctx);
      cb(this._text_78,ctx);
    }
    if (((nodeIndex == 80) && (ngContentIndex == 0))) {
      cb(this._text_81,ctx);
      cb(this._el_82,ctx);
      cb(this._text_89,ctx);
      cb(this._el_90,ctx);
      cb(this._text_97,ctx);
    }
    if (((nodeIndex == 99) && (ngContentIndex == 0))) {
      cb(this._text_100,ctx);
      cb(this._el_101,ctx);
      cb(this._text_103,ctx);
      cb(this._el_104,ctx);
      cb(this._text_106,ctx);
    }
  }
  createEmbeddedViewInternal(nodeIndex:number):import1.AppView<any> {
    if ((nodeIndex == 28)) { return new View_AppComponent1(this.viewUtils,this,28,this._anchor_28,this._vc_28); }
    if ((nodeIndex == 41)) { return new View_AppComponent2(this.viewUtils,this,41,this._anchor_41,this._vc_41); }
    if ((nodeIndex == 46)) { return new View_AppComponent3(this.viewUtils,this,46,this._anchor_46,this._vc_46); }
    if ((nodeIndex == 51)) { return new View_AppComponent4(this.viewUtils,this,51,this._anchor_51,this._vc_51); }
    if ((nodeIndex == 55)) { return new View_AppComponent5(this.viewUtils,this,55,this._anchor_55,this._vc_55); }
    if ((nodeIndex == 60)) { return new View_AppComponent9(this.viewUtils,this,60,this._anchor_60,this._vc_60); }
    if ((nodeIndex == 62)) { return new View_AppComponent10(this.viewUtils,this,62,this._anchor_62,this._vc_62); }
    if ((nodeIndex == 112)) { return new View_AppComponent11(this.viewUtils,this,112,this._anchor_112,this._vc_112); }
    return (null as any);
  }
  handleEvent_39(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>(this.context.choice = 'author')) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_44(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>(this.context.choice = 'likes')) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_49(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>(this.context.choice = 'createdOn')) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_72(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._NgForm_72_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_87(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._DefaultValueAccessor_87_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngModelChange')) {
      const pd_sub_0:any = ((<any>(this.context.upload.url = $event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_95(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._DefaultValueAccessor_95_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngModelChange')) {
      const pd_sub_0:any = ((<any>(this.context.upload.description = $event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_101(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this._ModalComponent_70_3.context.dismiss()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_104(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.addPicture()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}
class View_AppComponent1 extends import1.AppView<any> {
  _el_0:any;
  _el_1:any;
  _text_2:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import12.ViewContainer) {
    super(View_AppComponent1,renderType_AppComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_1 = import3.createRenderElement(this.renderer,this._el_0,'a',new import3.InlineArray2(2,'href','#'),(null as any));
    this._text_2 = this.renderer.createText(this._el_1,'Add a picture',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_1,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_1));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._el_1,
      this._text_2
    ]
    ),[disposable_0]);
    return (null as any);
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  handleEvent_1(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.parentView.context.open()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}
class View_AppComponent2 extends import1.AppView<any> {
  _el_0:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import12.ViewContainer) {
    super(View_AppComponent2,renderType_AppComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'i',new import3.InlineArray4(4,'aria-hidden','true','class','fa fa-check-circle'),(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return (null as any);
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_AppComponent3 extends import1.AppView<any> {
  _el_0:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import12.ViewContainer) {
    super(View_AppComponent3,renderType_AppComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'i',new import3.InlineArray4(4,'aria-hidden','true','class','fa fa-check-circle'),(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return (null as any);
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_AppComponent4 extends import1.AppView<any> {
  _el_0:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import12.ViewContainer) {
    super(View_AppComponent4,renderType_AppComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'i',new import3.InlineArray4(4,'aria-hidden','true','class','fa fa-check-circle'),(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return (null as any);
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_AppComponent5 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _el_8:any;
  _el_9:any;
  _text_10:any;
  _anchor_11:any;
  /*private*/ _vc_11:import12.ViewContainer;
  _TemplateRef_11_5:any;
  _NgIf_11_6:import13.Wrapper_NgIf;
  _text_12:any;
  _el_13:any;
  _el_14:any;
  _text_15:any;
  _anchor_16:any;
  /*private*/ _vc_16:import12.ViewContainer;
  _TemplateRef_16_5:any;
  _NgIf_16_6:import13.Wrapper_NgIf;
  _text_17:any;
  _el_18:any;
  _el_19:any;
  _text_20:any;
  _anchor_21:any;
  /*private*/ _vc_21:import12.ViewContainer;
  _TemplateRef_21_5:any;
  _NgIf_21_6:import13.Wrapper_NgIf;
  _text_22:any;
  _text_23:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import12.ViewContainer) {
    super(View_AppComponent5,renderType_AppComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'li',new import3.InlineArray2(2,'class','dropdown'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n          ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'a',new import3.InlineArray16(12,'aria-expanded','false','aria-haspopup','true','class','dropdown-toggle','data-toggle','dropdown','href','#','role','button'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'Showing',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_2,'span',new import3.InlineArray2(2,'class','caret'),(null as any));
    this._text_5 = this.renderer.createText(this._el_0,'\n          ',(null as any));
    this._el_6 = import3.createRenderElement(this.renderer,this._el_0,'ul',new import3.InlineArray2(2,'class','dropdown-menu'),(null as any));
    this._text_7 = this.renderer.createText(this._el_6,'\n            ',(null as any));
    this._el_8 = import3.createRenderElement(this.renderer,this._el_6,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_9 = import3.createRenderElement(this.renderer,this._el_8,'a',new import3.InlineArray2(2,'href','#'),(null as any));
    this._text_10 = this.renderer.createText(this._el_9,'my pictures ',(null as any));
    this._anchor_11 = this.renderer.createTemplateAnchor(this._el_9,(null as any));
    this._vc_11 = new import12.ViewContainer(11,9,this,this._anchor_11);
    this._TemplateRef_11_5 = new import30.TemplateRef_(this,11,this._anchor_11);
    this._NgIf_11_6 = new import13.Wrapper_NgIf(this._vc_11.vcRef,this._TemplateRef_11_5);
    this._text_12 = this.renderer.createText(this._el_6,'\n            ',(null as any));
    this._el_13 = import3.createRenderElement(this.renderer,this._el_6,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_14 = import3.createRenderElement(this.renderer,this._el_13,'a',new import3.InlineArray2(2,'href','#'),(null as any));
    this._text_15 = this.renderer.createText(this._el_14,'pictures posted by other users ',(null as any));
    this._anchor_16 = this.renderer.createTemplateAnchor(this._el_14,(null as any));
    this._vc_16 = new import12.ViewContainer(16,14,this,this._anchor_16);
    this._TemplateRef_16_5 = new import30.TemplateRef_(this,16,this._anchor_16);
    this._NgIf_16_6 = new import13.Wrapper_NgIf(this._vc_16.vcRef,this._TemplateRef_16_5);
    this._text_17 = this.renderer.createText(this._el_6,'\n            ',(null as any));
    this._el_18 = import3.createRenderElement(this.renderer,this._el_6,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_19 = import3.createRenderElement(this.renderer,this._el_18,'a',new import3.InlineArray2(2,'href','#'),(null as any));
    this._text_20 = this.renderer.createText(this._el_19,'all pictures ',(null as any));
    this._anchor_21 = this.renderer.createTemplateAnchor(this._el_19,(null as any));
    this._vc_21 = new import12.ViewContainer(21,19,this,this._anchor_21);
    this._TemplateRef_21_5 = new import30.TemplateRef_(this,21,this._anchor_21);
    this._NgIf_21_6 = new import13.Wrapper_NgIf(this._vc_21.vcRef,this._TemplateRef_21_5);
    this._text_22 = this.renderer.createText(this._el_6,'\n          ',(null as any));
    this._text_23 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_9,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_9));
    var disposable_1:Function = import3.subscribeToRenderElement(this,this._el_14,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_14));
    var disposable_2:Function = import3.subscribeToRenderElement(this,this._el_19,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_19));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._el_9,
      this._text_10,
      this._anchor_11,
      this._text_12,
      this._el_13,
      this._el_14,
      this._text_15,
      this._anchor_16,
      this._text_17,
      this._el_18,
      this._el_19,
      this._text_20,
      this._anchor_21,
      this._text_22,
      this._text_23
    ]
    ),[
      disposable_0,
      disposable_1,
      disposable_2
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import30.TemplateRef) && (11 === requestNodeIndex))) { return this._TemplateRef_11_5; }
    if (((token === import33.NgIf) && (11 === requestNodeIndex))) { return this._NgIf_11_6.context; }
    if (((token === import30.TemplateRef) && (16 === requestNodeIndex))) { return this._TemplateRef_16_5; }
    if (((token === import33.NgIf) && (16 === requestNodeIndex))) { return this._NgIf_16_6.context; }
    if (((token === import30.TemplateRef) && (21 === requestNodeIndex))) { return this._TemplateRef_21_5; }
    if (((token === import33.NgIf) && (21 === requestNodeIndex))) { return this._NgIf_21_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_11_0_0:any = (this.parentView.context.type === 'mine');
    this._NgIf_11_6.check_ngIf(currVal_11_0_0,throwOnChange,false);
    this._NgIf_11_6.ngDoCheck(this,this._anchor_11,throwOnChange);
    const currVal_16_0_0:any = (this.parentView.context.type === 'not mine');
    this._NgIf_16_6.check_ngIf(currVal_16_0_0,throwOnChange,false);
    this._NgIf_16_6.ngDoCheck(this,this._anchor_16,throwOnChange);
    const currVal_21_0_0:any = (this.parentView.context.type === 'all');
    this._NgIf_21_6.check_ngIf(currVal_21_0_0,throwOnChange,false);
    this._NgIf_21_6.ngDoCheck(this,this._anchor_21,throwOnChange);
    this._vc_11.detectChangesInNestedViews(throwOnChange);
    this._vc_16.detectChangesInNestedViews(throwOnChange);
    this._vc_21.detectChangesInNestedViews(throwOnChange);
  }
  destroyInternal():void {
    this._vc_11.destroyNestedViews();
    this._vc_16.destroyNestedViews();
    this._vc_21.destroyNestedViews();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  createEmbeddedViewInternal(nodeIndex:number):import1.AppView<any> {
    if ((nodeIndex == 11)) { return new View_AppComponent6(this.viewUtils,this,11,this._anchor_11,this._vc_11); }
    if ((nodeIndex == 16)) { return new View_AppComponent7(this.viewUtils,this,16,this._anchor_16,this._vc_16); }
    if ((nodeIndex == 21)) { return new View_AppComponent8(this.viewUtils,this,21,this._anchor_21,this._vc_21); }
    return (null as any);
  }
  handleEvent_9(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>(this.parentView.context.type = 'mine')) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_14(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>(this.parentView.context.type = 'not mine')) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_19(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>(this.parentView.context.type = 'all')) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}
class View_AppComponent6 extends import1.AppView<any> {
  _el_0:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import12.ViewContainer) {
    super(View_AppComponent6,renderType_AppComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'i',new import3.InlineArray4(4,'aria-hidden','true','class','fa fa-check-circle'),(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return (null as any);
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_AppComponent7 extends import1.AppView<any> {
  _el_0:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import12.ViewContainer) {
    super(View_AppComponent7,renderType_AppComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'i',new import3.InlineArray4(4,'aria-hidden','true','class','fa fa-check-circle'),(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return (null as any);
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_AppComponent8 extends import1.AppView<any> {
  _el_0:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import12.ViewContainer) {
    super(View_AppComponent8,renderType_AppComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'i',new import3.InlineArray4(4,'aria-hidden','true','class','fa fa-check-circle'),(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return (null as any);
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_AppComponent9 extends import1.AppView<any> {
  _el_0:any;
  _el_1:any;
  _el_2:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import12.ViewContainer) {
    super(View_AppComponent9,renderType_AppComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_1 = import3.createRenderElement(this.renderer,this._el_0,'a',new import3.InlineArray2(2,'href','/auth/twitter'),(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_1,'i',new import3.InlineArray2(2,'class','fa fa-twitter'),(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._el_1,
      this._el_2
    ]
    ),(null as any));
    return (null as any);
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_AppComponent10 extends import1.AppView<any> {
  _el_0:any;
  _el_1:any;
  _text_2:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import12.ViewContainer) {
    super(View_AppComponent10,renderType_AppComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_1 = import3.createRenderElement(this.renderer,this._el_0,'a',new import3.InlineArray2(2,'href','/auth/logout'),(null as any));
    this._text_2 = this.renderer.createText(this._el_1,'Logout',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._el_1,
      this._text_2
    ]
    ),(null as any));
    return (null as any);
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_AppComponent11 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import44.BrickComponent>;
  _BrickComponent_0_3:import45.Wrapper_BrickComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import12.ViewContainer) {
    super(View_AppComponent11,renderType_AppComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'brick',new import3.InlineArray2(2,'class','gallery-item'),(null as any));
    this.compView_0 = new import45.View_BrickComponent0(this.viewUtils,this,0,this._el_0);
    this._BrickComponent_0_3 = new import45.Wrapper_BrickComponent();
    this.compView_0.create(this._BrickComponent_0_3.context);
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_0,new import3.InlineArray8(6,'put',(null as any),'like',(null as any),'remove',(null as any)),this.eventHandler(this.handleEvent_0));
    this._BrickComponent_0_3.subscribe(this,this.eventHandler(this.handleEvent_0),true,true,true);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),[disposable_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import44.BrickComponent) && (0 === requestNodeIndex))) { return this._BrickComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0_0_0:any = this.context.$implicit._id;
    this._BrickComponent_0_3.check_id(currVal_0_0_0,throwOnChange,false);
    const currVal_0_0_1:any = this.context.$implicit.url;
    this._BrickComponent_0_3.check_url(currVal_0_0_1,throwOnChange,false);
    const currVal_0_0_2:any = this.context.$implicit.description;
    this._BrickComponent_0_3.check_description(currVal_0_0_2,throwOnChange,false);
    const currVal_0_0_3:any = this.context.$implicit.author;
    this._BrickComponent_0_3.check_author(currVal_0_0_3,throwOnChange,false);
    const currVal_0_0_4:any = this.context.$implicit.thumbnail;
    this._BrickComponent_0_3.check_thumbnail(currVal_0_0_4,throwOnChange,false);
    const currVal_0_0_5:any = this.context.$implicit.likedBy;
    this._BrickComponent_0_3.check_likedBy(currVal_0_0_5,throwOnChange,false);
    const currVal_0_0_6:any = this.parentView.context.user;
    this._BrickComponent_0_3.check_user(currVal_0_0_6,throwOnChange,false);
    this._BrickComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.detectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
    this._BrickComponent_0_3.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  handleEvent_0(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'put')) {
      const pd_sub_0:any = ((<any>this.parentView.context.updatePicture($event)) !== false);
      result = (pd_sub_0 && result);
    }
    if ((eventName == 'like')) {
      const pd_sub_1:any = ((<any>this.parentView.context.toggleLikes($event)) !== false);
      result = (pd_sub_1 && result);
    }
    if ((eventName == 'remove')) {
      const pd_sub_2:any = ((<any>this.parentView.context.removePicture($event)) !== false);
      result = (pd_sub_2 && result);
    }
    return result;
  }
}