/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../../app/components/brick.component';
import * as import1 from '@angular/core/src/change_detection/change_detection';
import * as import2 from '@angular/core/src/linker/view';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/render/api';
import * as import5 from '@angular/core/src/metadata/view';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from './css/brick.component.css.shim';
import * as import9 from '@angular/core/src/linker/query_list';
import * as import10 from '@angular/core/src/linker/view_container';
import * as import11 from '../../node_modules/@angular/common/src/directives/ng_if.ngfactory';
import * as import12 from 'ng2-bs3-modal/components/modal';
import * as import13 from '../../node_modules/ng2-bs3-modal/components/modal.ngfactory';
import * as import14 from '../../node_modules/@angular/forms/src/directives/ng_form.ngfactory';
import * as import15 from '../../node_modules/@angular/forms/src/directives/ng_control_status.ngfactory';
import * as import16 from 'ng2-bs3-modal/components/modal-header';
import * as import17 from '../../node_modules/ng2-bs3-modal/components/modal-header.ngfactory';
import * as import18 from 'ng2-bs3-modal/components/modal-body';
import * as import19 from '../../node_modules/ng2-bs3-modal/components/modal-body.ngfactory';
import * as import20 from '../../node_modules/@angular/forms/src/directives/default_value_accessor.ngfactory';
import * as import21 from '../../node_modules/@angular/forms/src/directives/validators.ngfactory';
import * as import22 from '../../node_modules/@angular/forms/src/directives/ng_model.ngfactory';
import * as import23 from 'ng2-bs3-modal/components/modal-footer';
import * as import24 from '../../node_modules/ng2-bs3-modal/components/modal-footer.ngfactory';
import * as import25 from '@angular/core/src/linker/template_ref';
import * as import26 from '@angular/core/src/linker/element_ref';
import * as import27 from '@angular/common/src/directives/ng_if';
import * as import28 from '@angular/forms/src/directives/default_value_accessor';
import * as import29 from '@angular/forms/src/directives/validators';
import * as import30 from '@angular/forms/src/validators';
import * as import31 from '@angular/forms/src/directives/control_value_accessor';
import * as import32 from '@angular/forms/src/directives/ng_model';
import * as import33 from '@angular/forms/src/directives/ng_control';
import * as import34 from '@angular/forms/src/directives/ng_control_status';
import * as import35 from '@angular/forms/src/directives/ng_form';
import * as import36 from '@angular/forms/src/directives/control_container';
import * as import37 from '@angular/core/src/security';
export class Wrapper_BrickComponent {
  /*private*/ _eventHandler:Function;
  context:import0.BrickComponent;
  /*private*/ _changed:boolean;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  subscription0:any;
  subscription1:any;
  subscription2:any;
  constructor() {
    this._changed = false;
    this.context = new import0.BrickComponent();
    this._expr_0 = import1.UNINITIALIZED;
    this._expr_1 = import1.UNINITIALIZED;
    this._expr_2 = import1.UNINITIALIZED;
    this._expr_3 = import1.UNINITIALIZED;
    this._expr_4 = import1.UNINITIALIZED;
    this._expr_5 = import1.UNINITIALIZED;
    this._expr_6 = import1.UNINITIALIZED;
  }
  ngOnDetach(view:import2.AppView<any>,componentView:import2.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
    (this.subscription0 && this.subscription0.unsubscribe());
    (this.subscription1 && this.subscription1.unsubscribe());
    (this.subscription2 && this.subscription2.unsubscribe());
  }
  check_id(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_0,currValue))) {
      this._changed = true;
      this.context.id = currValue;
      this._expr_0 = currValue;
    }
  }
  check_url(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_1,currValue))) {
      this._changed = true;
      this.context.url = currValue;
      this._expr_1 = currValue;
    }
  }
  check_description(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_2,currValue))) {
      this._changed = true;
      this.context.description = currValue;
      this._expr_2 = currValue;
    }
  }
  check_author(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_3,currValue))) {
      this._changed = true;
      this.context.author = currValue;
      this._expr_3 = currValue;
    }
  }
  check_thumbnail(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_4,currValue))) {
      this._changed = true;
      this.context.thumbnail = currValue;
      this._expr_4 = currValue;
    }
  }
  check_likedBy(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_5,currValue))) {
      this._changed = true;
      this.context.likedBy = currValue;
      this._expr_5 = currValue;
    }
  }
  check_user(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_6,currValue))) {
      this._changed = true;
      this.context.user = currValue;
      this._expr_6 = currValue;
    }
  }
  ngDoCheck(view:import2.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
  checkHost(view:import2.AppView<any>,componentView:import2.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import2.AppView<any>,_eventHandler:any,emit0:boolean,emit1:boolean,emit2:boolean):void {
    this._eventHandler = _eventHandler;
    if (emit0) { (this.subscription0 = this.context.put.subscribe(_eventHandler.bind(view,'put'))); }
    if (emit1) { (this.subscription1 = this.context.like.subscribe(_eventHandler.bind(view,'like'))); }
    if (emit2) { (this.subscription2 = this.context.remove.subscribe(_eventHandler.bind(view,'remove'))); }
  }
}
var renderType_BrickComponent_Host:import4.RenderComponentType = import3.createRenderComponentType('',0,import5.ViewEncapsulation.None,([] as any[]),{});
class View_BrickComponent_Host0 extends import2.AppView<any> {
  _el_0:any;
  compView_0:import2.AppView<import0.BrickComponent>;
  _BrickComponent_0_3:Wrapper_BrickComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_BrickComponent_Host0,renderType_BrickComponent_Host,import6.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import1.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'brick',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_BrickComponent0(this.viewUtils,this,0,this._el_0);
    this._BrickComponent_0_3 = new Wrapper_BrickComponent();
    this.compView_0.create(this._BrickComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._BrickComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.BrickComponent) && (0 === requestNodeIndex))) { return this._BrickComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._BrickComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.detectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
    this._BrickComponent_0_3.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const BrickComponentNgFactory:import7.ComponentFactory<import0.BrickComponent> = new import7.ComponentFactory<import0.BrickComponent>('brick',View_BrickComponent_Host0,import0.BrickComponent);
const styles_BrickComponent:any[] = [import8.styles];
var renderType_BrickComponent:import4.RenderComponentType = import3.createRenderComponentType('',0,import5.ViewEncapsulation.Emulated,styles_BrickComponent,{});
export class View_BrickComponent0 extends import2.AppView<import0.BrickComponent> {
  _viewQuery_editModal_0:import9.QueryList<any>;
  _viewQuery_viewer_1:import9.QueryList<any>;
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _anchor_4:any;
  /*private*/ _vc_4:import10.ViewContainer;
  _TemplateRef_4_5:any;
  _NgIf_4_6:import11.Wrapper_NgIf;
  _text_5:any;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _el_9:any;
  _el_10:any;
  _text_11:any;
  _el_12:any;
  _text_13:any;
  _text_14:any;
  _text_15:any;
  _el_16:any;
  _text_17:any;
  _el_18:any;
  _text_19:any;
  _el_20:any;
  _text_21:any;
  _el_22:any;
  _text_23:any;
  _text_24:any;
  _text_25:any;
  _el_26:any;
  compView_26:import2.AppView<import12.ModalComponent>;
  _ModalComponent_26_3:import13.Wrapper_ModalComponent;
  _text_27:any;
  _el_28:any;
  _NgForm_28_3:import14.Wrapper_NgForm;
  _ControlContainer_28_4:any;
  _NgControlStatusGroup_28_5:import15.Wrapper_NgControlStatusGroup;
  _text_29:any;
  _el_30:any;
  compView_30:import2.AppView<import16.ModalHeaderComponent>;
  _ModalHeaderComponent_30_3:import17.Wrapper_ModalHeaderComponent;
  _text_31:any;
  _el_32:any;
  _text_33:any;
  _text_34:any;
  _text_35:any;
  _el_36:any;
  compView_36:import2.AppView<import18.ModalBodyComponent>;
  _ModalBodyComponent_36_3:import19.Wrapper_ModalBodyComponent;
  _text_37:any;
  _el_38:any;
  _text_39:any;
  _el_40:any;
  _text_41:any;
  _text_42:any;
  _el_43:any;
  _DefaultValueAccessor_43_3:import20.Wrapper_DefaultValueAccessor;
  _RequiredValidator_43_4:import21.Wrapper_RequiredValidator;
  _NG_VALIDATORS_43_5:any[];
  _NG_VALUE_ACCESSOR_43_6:any[];
  _NgModel_43_7:import22.Wrapper_NgModel;
  _NgControl_43_8:any;
  _NgControlStatus_43_9:import15.Wrapper_NgControlStatus;
  _text_44:any;
  _text_45:any;
  _el_46:any;
  _text_47:any;
  _el_48:any;
  _text_49:any;
  _text_50:any;
  _el_51:any;
  _DefaultValueAccessor_51_3:import20.Wrapper_DefaultValueAccessor;
  _RequiredValidator_51_4:import21.Wrapper_RequiredValidator;
  _NG_VALIDATORS_51_5:any[];
  _NG_VALUE_ACCESSOR_51_6:any[];
  _NgModel_51_7:import22.Wrapper_NgModel;
  _NgControl_51_8:any;
  _NgControlStatus_51_9:import15.Wrapper_NgControlStatus;
  _text_52:any;
  _text_53:any;
  _text_54:any;
  _el_55:any;
  compView_55:import2.AppView<import23.ModalFooterComponent>;
  _ModalFooterComponent_55_3:import24.Wrapper_ModalFooterComponent;
  _text_56:any;
  _el_57:any;
  _text_58:any;
  _text_59:any;
  _el_60:any;
  _text_61:any;
  _text_62:any;
  _el_63:any;
  _text_64:any;
  _text_65:any;
  _text_66:any;
  _text_67:any;
  _text_68:any;
  _el_69:any;
  compView_69:import2.AppView<import12.ModalComponent>;
  _ModalComponent_69_3:import13.Wrapper_ModalComponent;
  _text_70:any;
  _el_71:any;
  compView_71:import2.AppView<import16.ModalHeaderComponent>;
  _ModalHeaderComponent_71_3:import17.Wrapper_ModalHeaderComponent;
  _text_72:any;
  _el_73:any;
  _text_74:any;
  _text_75:any;
  _text_76:any;
  _el_77:any;
  compView_77:import2.AppView<import18.ModalBodyComponent>;
  _ModalBodyComponent_77_3:import19.Wrapper_ModalBodyComponent;
  _text_78:any;
  _el_79:any;
  _text_80:any;
  _text_81:any;
  _text_82:any;
  /*private*/ _expr_119:any;
  /*private*/ _expr_120:any;
  /*private*/ _expr_121:any;
  /*private*/ _expr_122:any;
  /*private*/ _expr_123:any;
  /*private*/ _expr_124:any;
  /*private*/ _expr_125:any;
  /*private*/ _expr_126:any;
  /*private*/ _expr_127:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_BrickComponent0,renderType_BrickComponent,import6.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import1.ChangeDetectorStatus.CheckAlways);
    this._expr_119 = import1.UNINITIALIZED;
    this._expr_120 = import1.UNINITIALIZED;
    this._expr_121 = import1.UNINITIALIZED;
    this._expr_122 = import1.UNINITIALIZED;
    this._expr_123 = import1.UNINITIALIZED;
    this._expr_124 = import1.UNINITIALIZED;
    this._expr_125 = import1.UNINITIALIZED;
    this._expr_126 = import1.UNINITIALIZED;
    this._expr_127 = import1.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._viewQuery_editModal_0 = new import9.QueryList<any>();
    this._viewQuery_viewer_1 = new import9.QueryList<any>();
    this._el_0 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'class','brick'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','top'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._anchor_4 = this.renderer.createTemplateAnchor(this._el_2,(null as any));
    this._vc_4 = new import10.ViewContainer(4,2,this,this._anchor_4);
    this._TemplateRef_4_5 = new import25.TemplateRef_(this,4,this._anchor_4);
    this._NgIf_4_6 = new import11.Wrapper_NgIf(this._vc_4.vcRef,this._TemplateRef_4_5);
    this._text_5 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._text_6 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_7 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','center'),(null as any));
    this._text_8 = this.renderer.createText(this._el_7,'\n        ',(null as any));
    this._el_9 = import3.createRenderElement(this.renderer,this._el_7,'a',new import3.InlineArray2(2,'class','full-screen'),(null as any));
    this._el_10 = import3.createRenderElement(this.renderer,this._el_9,'img',new import3.InlineArray4(4,'class','img-responsive','onError','this.src=\'https://cdn.hyperdev.com/us-east-1%3A60e6615e-7d9e-47ac-903b-3b4b47372e42%2Fplaceholder.png\''),(null as any));
    this._text_11 = this.renderer.createText(this._el_7,'\n        ',(null as any));
    this._el_12 = import3.createRenderElement(this.renderer,this._el_7,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_13 = this.renderer.createText(this._el_12,'',(null as any));
    this._text_14 = this.renderer.createText(this._el_7,'\n    ',(null as any));
    this._text_15 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_16 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','bottom'),(null as any));
    this._text_17 = this.renderer.createText(this._el_16,'\n        ',(null as any));
    this._el_18 = import3.createRenderElement(this.renderer,this._el_16,'img',new import3.InlineArray16(10,'alt','profile picture','class','img-responsive img-thumbnail profile-img','data-placement','bottom','data-toggle','tooltip','onError','this.src=\'https://cdn.hyperdev.com/us-east-1%3A60e6615e-7d9e-47ac-903b-3b4b47372e42%2Fplaceholder.png\''),(null as any));
    this._text_19 = this.renderer.createText(this._el_16,'\n        ',(null as any));
    this._el_20 = import3.createRenderElement(this.renderer,this._el_16,'button',new import3.InlineArray4(4,'class','btn like','type','button'),(null as any));
    this._text_21 = this.renderer.createText(this._el_20,'',(null as any));
    this._el_22 = import3.createRenderElement(this.renderer,this._el_20,'i',new import3.InlineArray4(4,'aria-hidden','true','class','fa fa-thumbs-up'),(null as any));
    this._text_23 = this.renderer.createText(this._el_16,'\n    ',(null as any));
    this._text_24 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_25 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_26 = import3.createRenderElement(this.renderer,parentRenderNode,'modal',new import3.InlineArray8(6,'class','modal','role','dialog','tabindex','-1'),(null as any));
    this.compView_26 = new import13.View_ModalComponent0(this.viewUtils,this,26,this._el_26);
    this._ModalComponent_26_3 = new import13.Wrapper_ModalComponent(new import26.ElementRef(this._el_26));
    this._text_27 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_28 = import3.createRenderElement(this.renderer,(null as any),'form',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._NgForm_28_3 = new import14.Wrapper_NgForm((null as any),(null as any));
    this._ControlContainer_28_4 = this._NgForm_28_3.context;
    this._NgControlStatusGroup_28_5 = new import15.Wrapper_NgControlStatusGroup(this._ControlContainer_28_4);
    this._text_29 = this.renderer.createText(this._el_28,'\n        ',(null as any));
    this._el_30 = import3.createRenderElement(this.renderer,this._el_28,'modal-header',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_30 = new import17.View_ModalHeaderComponent0(this.viewUtils,this,30,this._el_30);
    this._ModalHeaderComponent_30_3 = new import17.Wrapper_ModalHeaderComponent(this._ModalComponent_26_3.context);
    this._text_31 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._el_32 = import3.createRenderElement(this.renderer,(null as any),'h4',new import3.InlineArray2(2,'class','modal-title'),(null as any));
    this._text_33 = this.renderer.createText(this._el_32,'Edit or remove picture',(null as any));
    this._text_34 = this.renderer.createText((null as any),'\n        ',(null as any));
    this.compView_30.create(this._ModalHeaderComponent_30_3.context);
    this._text_35 = this.renderer.createText(this._el_28,'\n        ',(null as any));
    this._el_36 = import3.createRenderElement(this.renderer,this._el_28,'modal-body',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_36 = new import19.View_ModalBodyComponent0(this.viewUtils,this,36,this._el_36);
    this._ModalBodyComponent_36_3 = new import19.Wrapper_ModalBodyComponent();
    this._text_37 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._el_38 = import3.createRenderElement(this.renderer,(null as any),'div',new import3.InlineArray2(2,'class','form-group'),(null as any));
    this._text_39 = this.renderer.createText(this._el_38,'\n                ',(null as any));
    this._el_40 = import3.createRenderElement(this.renderer,this._el_38,'label',new import3.InlineArray2(2,'for','firstName'),(null as any));
    this._text_41 = this.renderer.createText(this._el_40,'URL',(null as any));
    this._text_42 = this.renderer.createText(this._el_38,'\n                ',(null as any));
    this._el_43 = import3.createRenderElement(this.renderer,this._el_38,'input',new import3.InlineArray16(10,'class','form-control','id','url','name','url','required','','type','text'),(null as any));
    this._DefaultValueAccessor_43_3 = new import20.Wrapper_DefaultValueAccessor(this.renderer,new import26.ElementRef(this._el_43));
    this._RequiredValidator_43_4 = new import21.Wrapper_RequiredValidator();
    this._NG_VALIDATORS_43_5 = [this._RequiredValidator_43_4.context];
    this._NG_VALUE_ACCESSOR_43_6 = [this._DefaultValueAccessor_43_3.context];
    this._NgModel_43_7 = new import22.Wrapper_NgModel(this._ControlContainer_28_4,this._NG_VALIDATORS_43_5,(null as any),this._NG_VALUE_ACCESSOR_43_6);
    this._NgControl_43_8 = this._NgModel_43_7.context;
    this._NgControlStatus_43_9 = new import15.Wrapper_NgControlStatus(this._NgControl_43_8);
    this._text_44 = this.renderer.createText(this._el_38,'\n            ',(null as any));
    this._text_45 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._el_46 = import3.createRenderElement(this.renderer,(null as any),'div',new import3.InlineArray2(2,'class','form-group'),(null as any));
    this._text_47 = this.renderer.createText(this._el_46,'\n                ',(null as any));
    this._el_48 = import3.createRenderElement(this.renderer,this._el_46,'label',new import3.InlineArray2(2,'for','lastName'),(null as any));
    this._text_49 = this.renderer.createText(this._el_48,'Description',(null as any));
    this._text_50 = this.renderer.createText(this._el_46,'\n                ',(null as any));
    this._el_51 = import3.createRenderElement(this.renderer,this._el_46,'input',new import3.InlineArray16(10,'class','form-control','id','description','name','description','required','','type','text'),(null as any));
    this._DefaultValueAccessor_51_3 = new import20.Wrapper_DefaultValueAccessor(this.renderer,new import26.ElementRef(this._el_51));
    this._RequiredValidator_51_4 = new import21.Wrapper_RequiredValidator();
    this._NG_VALIDATORS_51_5 = [this._RequiredValidator_51_4.context];
    this._NG_VALUE_ACCESSOR_51_6 = [this._DefaultValueAccessor_51_3.context];
    this._NgModel_51_7 = new import22.Wrapper_NgModel(this._ControlContainer_28_4,this._NG_VALIDATORS_51_5,(null as any),this._NG_VALUE_ACCESSOR_51_6);
    this._NgControl_51_8 = this._NgModel_51_7.context;
    this._NgControlStatus_51_9 = new import15.Wrapper_NgControlStatus(this._NgControl_51_8);
    this._text_52 = this.renderer.createText(this._el_46,'\n            ',(null as any));
    this._text_53 = this.renderer.createText((null as any),'\n        ',(null as any));
    this.compView_36.create(this._ModalBodyComponent_36_3.context);
    this._text_54 = this.renderer.createText(this._el_28,'\n        ',(null as any));
    this._el_55 = import3.createRenderElement(this.renderer,this._el_28,'modal-footer',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_55 = new import24.View_ModalFooterComponent0(this.viewUtils,this,55,this._el_55);
    this._ModalFooterComponent_55_3 = new import24.Wrapper_ModalFooterComponent(this._ModalComponent_26_3.context);
    this._text_56 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._el_57 = import3.createRenderElement(this.renderer,(null as any),'button',new import3.InlineArray8(6,'class','btn btn-default','data-dismiss','modal','type','button'),(null as any));
    this._text_58 = this.renderer.createText(this._el_57,'Cancel',(null as any));
    this._text_59 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._el_60 = import3.createRenderElement(this.renderer,(null as any),'button',new import3.InlineArray8(6,'class','btn btn-danger','data-dismiss','modal','type','button'),(null as any));
    this._text_61 = this.renderer.createText(this._el_60,'Remove',(null as any));
    this._text_62 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._el_63 = import3.createRenderElement(this.renderer,(null as any),'button',new import3.InlineArray4(4,'class','btn btn-primary','type','button'),(null as any));
    this._text_64 = this.renderer.createText(this._el_63,'Save',(null as any));
    this._text_65 = this.renderer.createText((null as any),'\n        ',(null as any));
    this.compView_55.create(this._ModalFooterComponent_55_3.context);
    this._text_66 = this.renderer.createText(this._el_28,'\n    ',(null as any));
    this._text_67 = this.renderer.createText((null as any),'\n',(null as any));
    this.compView_26.create(this._ModalComponent_26_3.context);
    this._text_68 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_69 = import3.createRenderElement(this.renderer,parentRenderNode,'modal',new import3.InlineArray8(8,'class','modal','cssClass','modal-full','role','dialog','tabindex','-1'),(null as any));
    this.compView_69 = new import13.View_ModalComponent0(this.viewUtils,this,69,this._el_69);
    this._ModalComponent_69_3 = new import13.Wrapper_ModalComponent(new import26.ElementRef(this._el_69));
    this._text_70 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_71 = import3.createRenderElement(this.renderer,(null as any),'modal-header',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_71 = new import17.View_ModalHeaderComponent0(this.viewUtils,this,71,this._el_71);
    this._ModalHeaderComponent_71_3 = new import17.Wrapper_ModalHeaderComponent(this._ModalComponent_69_3.context);
    this._text_72 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_73 = import3.createRenderElement(this.renderer,(null as any),'h4',new import3.InlineArray2(2,'class','modal-title text-center'),(null as any));
    this._text_74 = this.renderer.createText(this._el_73,'',(null as any));
    this._text_75 = this.renderer.createText((null as any),'\n    ',(null as any));
    this.compView_71.create(this._ModalHeaderComponent_71_3.context);
    this._text_76 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_77 = import3.createRenderElement(this.renderer,(null as any),'modal-body',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_77 = new import19.View_ModalBodyComponent0(this.viewUtils,this,77,this._el_77);
    this._ModalBodyComponent_77_3 = new import19.Wrapper_ModalBodyComponent();
    this._text_78 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_79 = import3.createRenderElement(this.renderer,(null as any),'img',new import3.InlineArray2(2,'onError','this.src=\'https://cdn.hyperdev.com/us-east-1%3A60e6615e-7d9e-47ac-903b-3b4b47372e42%2Fplaceholder.png\''),(null as any));
    this._text_80 = this.renderer.createText((null as any),'\n    ',(null as any));
    this.compView_77.create(this._ModalBodyComponent_77_3.context);
    this._text_81 = this.renderer.createText((null as any),'\n',(null as any));
    this.compView_69.create(this._ModalComponent_69_3.context);
    this._text_82 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_9,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_9));
    var disposable_1:Function = import3.subscribeToRenderElement(this,this._el_20,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_20));
    var disposable_2:Function = import3.subscribeToRenderElement(this,this._el_28,new import3.InlineArray4(4,'submit',(null as any),'reset',(null as any)),this.eventHandler(this.handleEvent_28));
    var disposable_3:Function = import3.subscribeToRenderElement(this,this._el_43,new import3.InlineArray8(6,'ngModelChange',(null as any),'input',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_43));
    this._NgModel_43_7.subscribe(this,this.eventHandler(this.handleEvent_43),true);
    var disposable_4:Function = import3.subscribeToRenderElement(this,this._el_51,new import3.InlineArray8(6,'ngModelChange',(null as any),'input',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_51));
    this._NgModel_51_7.subscribe(this,this.eventHandler(this.handleEvent_51),true);
    var disposable_5:Function = import3.subscribeToRenderElement(this,this._el_57,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_57));
    var disposable_6:Function = import3.subscribeToRenderElement(this,this._el_60,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_60));
    var disposable_7:Function = import3.subscribeToRenderElement(this,this._el_63,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_63));
    this._viewQuery_editModal_0.reset([this._ModalComponent_26_3.context]);
    this.context.modal = this._viewQuery_editModal_0.first;
    this._viewQuery_viewer_1.reset([this._ModalComponent_69_3.context]);
    this.context.viewer = this._viewQuery_viewer_1.first;
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._anchor_4,
      this._text_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._el_9,
      this._el_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._text_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._text_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._el_28,
      this._text_29,
      this._el_30,
      this._text_31,
      this._el_32,
      this._text_33,
      this._text_34,
      this._text_35,
      this._el_36,
      this._text_37,
      this._el_38,
      this._text_39,
      this._el_40,
      this._text_41,
      this._text_42,
      this._el_43,
      this._text_44,
      this._text_45,
      this._el_46,
      this._text_47,
      this._el_48,
      this._text_49,
      this._text_50,
      this._el_51,
      this._text_52,
      this._text_53,
      this._text_54,
      this._el_55,
      this._text_56,
      this._el_57,
      this._text_58,
      this._text_59,
      this._el_60,
      this._text_61,
      this._text_62,
      this._el_63,
      this._text_64,
      this._text_65,
      this._text_66,
      this._text_67,
      this._text_68,
      this._el_69,
      this._text_70,
      this._el_71,
      this._text_72,
      this._el_73,
      this._text_74,
      this._text_75,
      this._text_76,
      this._el_77,
      this._text_78,
      this._el_79,
      this._text_80,
      this._text_81,
      this._text_82
    ]
    ),[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4,
      disposable_5,
      disposable_6,
      disposable_7
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import25.TemplateRef) && (4 === requestNodeIndex))) { return this._TemplateRef_4_5; }
    if (((token === import27.NgIf) && (4 === requestNodeIndex))) { return this._NgIf_4_6.context; }
    if (((token === import16.ModalHeaderComponent) && ((30 <= requestNodeIndex) && (requestNodeIndex <= 34)))) { return this._ModalHeaderComponent_30_3.context; }
    if (((token === import28.DefaultValueAccessor) && (43 === requestNodeIndex))) { return this._DefaultValueAccessor_43_3.context; }
    if (((token === import29.RequiredValidator) && (43 === requestNodeIndex))) { return this._RequiredValidator_43_4.context; }
    if (((token === import30.NG_VALIDATORS) && (43 === requestNodeIndex))) { return this._NG_VALIDATORS_43_5; }
    if (((token === import31.NG_VALUE_ACCESSOR) && (43 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_43_6; }
    if (((token === import32.NgModel) && (43 === requestNodeIndex))) { return this._NgModel_43_7.context; }
    if (((token === import33.NgControl) && (43 === requestNodeIndex))) { return this._NgControl_43_8; }
    if (((token === import34.NgControlStatus) && (43 === requestNodeIndex))) { return this._NgControlStatus_43_9.context; }
    if (((token === import28.DefaultValueAccessor) && (51 === requestNodeIndex))) { return this._DefaultValueAccessor_51_3.context; }
    if (((token === import29.RequiredValidator) && (51 === requestNodeIndex))) { return this._RequiredValidator_51_4.context; }
    if (((token === import30.NG_VALIDATORS) && (51 === requestNodeIndex))) { return this._NG_VALIDATORS_51_5; }
    if (((token === import31.NG_VALUE_ACCESSOR) && (51 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_51_6; }
    if (((token === import32.NgModel) && (51 === requestNodeIndex))) { return this._NgModel_51_7.context; }
    if (((token === import33.NgControl) && (51 === requestNodeIndex))) { return this._NgControl_51_8; }
    if (((token === import34.NgControlStatus) && (51 === requestNodeIndex))) { return this._NgControlStatus_51_9.context; }
    if (((token === import18.ModalBodyComponent) && ((36 <= requestNodeIndex) && (requestNodeIndex <= 53)))) { return this._ModalBodyComponent_36_3.context; }
    if (((token === import23.ModalFooterComponent) && ((55 <= requestNodeIndex) && (requestNodeIndex <= 65)))) { return this._ModalFooterComponent_55_3.context; }
    if (((token === import35.NgForm) && ((28 <= requestNodeIndex) && (requestNodeIndex <= 66)))) { return this._NgForm_28_3.context; }
    if (((token === import36.ControlContainer) && ((28 <= requestNodeIndex) && (requestNodeIndex <= 66)))) { return this._ControlContainer_28_4; }
    if (((token === import34.NgControlStatusGroup) && ((28 <= requestNodeIndex) && (requestNodeIndex <= 66)))) { return this._NgControlStatusGroup_28_5.context; }
    if (((token === import12.ModalComponent) && ((26 <= requestNodeIndex) && (requestNodeIndex <= 67)))) { return this._ModalComponent_26_3.context; }
    if (((token === import16.ModalHeaderComponent) && ((71 <= requestNodeIndex) && (requestNodeIndex <= 75)))) { return this._ModalHeaderComponent_71_3.context; }
    if (((token === import18.ModalBodyComponent) && ((77 <= requestNodeIndex) && (requestNodeIndex <= 80)))) { return this._ModalBodyComponent_77_3.context; }
    if (((token === import12.ModalComponent) && ((69 <= requestNodeIndex) && (requestNodeIndex <= 81)))) { return this._ModalComponent_69_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_4_0_0:any = (this.context.user? (this.context.user.username === this.context.author): false);
    this._NgIf_4_6.check_ngIf(currVal_4_0_0,throwOnChange,false);
    this._NgIf_4_6.ngDoCheck(this,this._anchor_4,throwOnChange);
    this._ModalComponent_26_3.ngDoCheck(this,this._el_26,throwOnChange);
    this._NgForm_28_3.ngDoCheck(this,this._el_28,throwOnChange);
    this._NgControlStatusGroup_28_5.ngDoCheck(this,this._el_28,throwOnChange);
    const currVal_30_0_0:any = true;
    this._ModalHeaderComponent_30_3.check_showClose(currVal_30_0_0,throwOnChange,false);
    this._ModalHeaderComponent_30_3.ngDoCheck(this,this._el_30,throwOnChange);
    this._ModalBodyComponent_36_3.ngDoCheck(this,this._el_36,throwOnChange);
    this._DefaultValueAccessor_43_3.ngDoCheck(this,this._el_43,throwOnChange);
    const currVal_43_1_0:any = '';
    this._RequiredValidator_43_4.check_required(currVal_43_1_0,throwOnChange,false);
    this._RequiredValidator_43_4.ngDoCheck(this,this._el_43,throwOnChange);
    const currVal_43_2_0:any = 'url';
    this._NgModel_43_7.check_name(currVal_43_2_0,throwOnChange,false);
    const currVal_43_2_1:any = this.context.update.url;
    this._NgModel_43_7.check_model(currVal_43_2_1,throwOnChange,false);
    this._NgModel_43_7.ngDoCheck(this,this._el_43,throwOnChange);
    this._NgControlStatus_43_9.ngDoCheck(this,this._el_43,throwOnChange);
    this._DefaultValueAccessor_51_3.ngDoCheck(this,this._el_51,throwOnChange);
    const currVal_51_1_0:any = '';
    this._RequiredValidator_51_4.check_required(currVal_51_1_0,throwOnChange,false);
    this._RequiredValidator_51_4.ngDoCheck(this,this._el_51,throwOnChange);
    const currVal_51_2_0:any = 'description';
    this._NgModel_51_7.check_name(currVal_51_2_0,throwOnChange,false);
    const currVal_51_2_1:any = this.context.update.description;
    this._NgModel_51_7.check_model(currVal_51_2_1,throwOnChange,false);
    this._NgModel_51_7.ngDoCheck(this,this._el_51,throwOnChange);
    this._NgControlStatus_51_9.ngDoCheck(this,this._el_51,throwOnChange);
    this._ModalFooterComponent_55_3.ngDoCheck(this,this._el_55,throwOnChange);
    const currVal_69_0_0:any = 'modal-full';
    this._ModalComponent_69_3.check_cssClass(currVal_69_0_0,throwOnChange,false);
    this._ModalComponent_69_3.ngDoCheck(this,this._el_69,throwOnChange);
    const currVal_71_0_0:any = true;
    this._ModalHeaderComponent_71_3.check_showClose(currVal_71_0_0,throwOnChange,false);
    this._ModalHeaderComponent_71_3.ngDoCheck(this,this._el_71,throwOnChange);
    this._ModalBodyComponent_77_3.ngDoCheck(this,this._el_77,throwOnChange);
    this._vc_4.detectChangesInNestedViews(throwOnChange);
    const currVal_119:any = this.context.url;
    if (import3.checkBinding(throwOnChange,this._expr_119,currVal_119)) {
      this.renderer.setElementProperty(this._el_10,'src',this.viewUtils.sanitizer.sanitize(import37.SecurityContext.URL,currVal_119));
      this._expr_119 = currVal_119;
    }
    const currVal_120:any = import3.inlineInterpolate(1,'',this.context.description,'');
    if (import3.checkBinding(throwOnChange,this._expr_120,currVal_120)) {
      this.renderer.setText(this._text_13,currVal_120);
      this._expr_120 = currVal_120;
    }
    const currVal_121:any = this.context.thumbnail;
    if (import3.checkBinding(throwOnChange,this._expr_121,currVal_121)) {
      this.renderer.setElementProperty(this._el_18,'src',this.viewUtils.sanitizer.sanitize(import37.SecurityContext.URL,currVal_121));
      this._expr_121 = currVal_121;
    }
    const currVal_122:any = this.context.author;
    if (import3.checkBinding(throwOnChange,this._expr_122,currVal_122)) {
      this.renderer.setElementProperty(this._el_18,'title',currVal_122);
      this._expr_122 = currVal_122;
    }
    const currVal_123:boolean = (this.context.user? !this.context.user.authenticated: true);
    if (import3.checkBinding(throwOnChange,this._expr_123,currVal_123)) {
      this.renderer.setElementProperty(this._el_20,'disabled',currVal_123);
      this._expr_123 = currVal_123;
    }
    const currVal_124:any = import3.inlineInterpolate(1,'',this.context.likedBy.length,'');
    if (import3.checkBinding(throwOnChange,this._expr_124,currVal_124)) {
      this.renderer.setText(this._text_21,currVal_124);
      this._expr_124 = currVal_124;
    }
    this._ModalComponent_26_3.checkHost(this,this.compView_26,this._el_26,throwOnChange);
    this._NgControlStatusGroup_28_5.checkHost(this,this,this._el_28,throwOnChange);
    this._RequiredValidator_43_4.checkHost(this,this,this._el_43,throwOnChange);
    this._NgControlStatus_43_9.checkHost(this,this,this._el_43,throwOnChange);
    this._RequiredValidator_51_4.checkHost(this,this,this._el_51,throwOnChange);
    this._NgControlStatus_51_9.checkHost(this,this,this._el_51,throwOnChange);
    const currVal_125:boolean = !this._NgForm_28_3.context.valid;
    if (import3.checkBinding(throwOnChange,this._expr_125,currVal_125)) {
      this.renderer.setElementProperty(this._el_63,'disabled',currVal_125);
      this._expr_125 = currVal_125;
    }
    this._ModalComponent_69_3.checkHost(this,this.compView_69,this._el_69,throwOnChange);
    const currVal_126:any = import3.inlineInterpolate(1,'',this.context.description,'');
    if (import3.checkBinding(throwOnChange,this._expr_126,currVal_126)) {
      this.renderer.setText(this._text_74,currVal_126);
      this._expr_126 = currVal_126;
    }
    const currVal_127:any = this.context.url;
    if (import3.checkBinding(throwOnChange,this._expr_127,currVal_127)) {
      this.renderer.setElementProperty(this._el_79,'src',this.viewUtils.sanitizer.sanitize(import37.SecurityContext.URL,currVal_127));
      this._expr_127 = currVal_127;
    }
    this.compView_26.detectChanges(throwOnChange);
    this.compView_30.detectChanges(throwOnChange);
    this.compView_36.detectChanges(throwOnChange);
    this.compView_55.detectChanges(throwOnChange);
    this.compView_69.detectChanges(throwOnChange);
    this.compView_71.detectChanges(throwOnChange);
    this.compView_77.detectChanges(throwOnChange);
  }
  destroyInternal():void {
    this._vc_4.destroyNestedViews();
    this.compView_26.destroy();
    this.compView_30.destroy();
    this.compView_36.destroy();
    this.compView_55.destroy();
    this.compView_69.destroy();
    this.compView_71.destroy();
    this.compView_77.destroy();
    this._NgModel_43_7.ngOnDestroy();
    this._NgModel_51_7.ngOnDestroy();
    this._NgForm_28_3.ngOnDestroy();
    this._ModalComponent_26_3.ngOnDestroy();
    this._ModalComponent_69_3.ngOnDestroy();
  }
  visitProjectableNodesInternal(nodeIndex:number,ngContentIndex:number,cb:any,ctx:any):void {
    if (((nodeIndex == 26) && (ngContentIndex == 0))) {
      cb(this._text_27,ctx);
      cb(this._el_28,ctx);
      cb(this._text_67,ctx);
    }
    if (((nodeIndex == 30) && (ngContentIndex == 0))) {
      cb(this._text_31,ctx);
      cb(this._el_32,ctx);
      cb(this._text_34,ctx);
    }
    if (((nodeIndex == 36) && (ngContentIndex == 0))) {
      cb(this._text_37,ctx);
      cb(this._el_38,ctx);
      cb(this._text_45,ctx);
      cb(this._el_46,ctx);
      cb(this._text_53,ctx);
    }
    if (((nodeIndex == 55) && (ngContentIndex == 0))) {
      cb(this._text_56,ctx);
      cb(this._el_57,ctx);
      cb(this._text_59,ctx);
      cb(this._el_60,ctx);
      cb(this._text_62,ctx);
      cb(this._el_63,ctx);
      cb(this._text_65,ctx);
    }
    if (((nodeIndex == 69) && (ngContentIndex == 0))) {
      cb(this._text_70,ctx);
      cb(this._el_71,ctx);
      cb(this._text_76,ctx);
      cb(this._el_77,ctx);
      cb(this._text_81,ctx);
    }
    if (((nodeIndex == 71) && (ngContentIndex == 0))) {
      cb(this._text_72,ctx);
      cb(this._el_73,ctx);
      cb(this._text_75,ctx);
    }
    if (((nodeIndex == 77) && (ngContentIndex == 0))) {
      cb(this._text_78,ctx);
      cb(this._el_79,ctx);
      cb(this._text_80,ctx);
    }
  }
  createEmbeddedViewInternal(nodeIndex:number):import2.AppView<any> {
    if ((nodeIndex == 4)) { return new View_BrickComponent1(this.viewUtils,this,4,this._anchor_4,this._vc_4); }
    return (null as any);
  }
  handleEvent_9(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this._ModalComponent_69_3.context.open()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_20(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.onLike()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_28(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._NgForm_28_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_43(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._DefaultValueAccessor_43_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngModelChange')) {
      const pd_sub_0:any = ((<any>(this.context.update.url = $event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_51(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._DefaultValueAccessor_51_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngModelChange')) {
      const pd_sub_0:any = ((<any>(this.context.update.description = $event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_57(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this._ModalComponent_26_3.context.dismiss()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_60(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.onRemove()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_63(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.onUpdate()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}
class View_BrickComponent1 extends import2.AppView<any> {
  _el_0:any;
  _el_1:any;
  _text_2:any;
  _el_3:any;
  _text_4:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import10.ViewContainer) {
    super(View_BrickComponent1,renderType_BrickComponent,import6.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import1.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'button',new import3.InlineArray4(4,'class','settings btn','type','button'),(null as any));
    this._el_1 = import3.createRenderElement(this.renderer,this._el_0,'i',new import3.InlineArray4(4,'aria-hidden','true','class','fa fa-cog'),(null as any));
    this._text_2 = this.renderer.createText(this._el_0,' ',(null as any));
    this._el_3 = import3.createRenderElement(this.renderer,this._el_0,'span',new import3.InlineArray2(2,'class','sr-only'),(null as any));
    this._text_4 = this.renderer.createText(this._el_3,'Settings',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_0,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_0));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._text_4
    ]
    ),[disposable_0]);
    return (null as any);
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  handleEvent_0(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.parentView.context.open()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}